base: &base
  adapter: mysql2
  enconding: utf8

production_base: &production_base

no_production_base: &no_production_base
  pool: 5
  username: root
  password:

#this is for replication. In development/integration we can just set the same config as in the "development" section
master_database:
  database: ideas4all_authorizator
  <<: *base
  <<: *production_base

development:
  database: authorizator_development
  <<: *base
  <<: *no_production_base

test:
  database: authorizator_test
  <<: *base
  <<: *no_production_base

production:
  database: ideas4all_authorizator
  <<: *base
  <<: *production_base

